#!/usr/bin/env python3
import uuid
from datetime import datetime
from enum import Enum


class BookType(str, Enum):
    """BookType is enum that declares type of book.
    Predefined values:
        Science Fiction
        Satire
        Drama
        Action and Adventure
        Romance
    """
    SCIENCE_FICTION: str = "Science Fiction"
    SATIRE: str = "Satire"
    DRAMA: str = "Drama"
    ACTION_AND_ADVENTURE: str = "Action and Adventure"
    ROMANCE: str = "Romance"


class Book:
    """The :class:`Book` object, which contains an object with the following fields:
        BookType book_type
        string title
        string id (unique, autogenerated)
        ISO_date creation_date
        ISO_date updated_date_time (autogenerated)
    """
    def __init__(self, book_type, title, creation_date=None):
        self._book_type = book_type
        self._title = title
        self._id = str(uuid.uuid4())
        self._creation_date = creation_date
        self._updated_date_time = datetime.now().isoformat()

    def json(self):
        return {"_book_type": self._book_type, "_title": self._title, "_id": self._id,
                "_creation_date": self._creation_date,
                "_updated_date_time": self._updated_date_time}
